### PR TITLE
[enh] Create shallow clone to increase app installation time

### PR DESCRIPTION
**Pull request by opi**

### CODE REVIEW

**Comment by julienmalik** [comment]
Why would you want to **increase** app installation time ?
;)

**Comment by opi** [comment]
because my english sucks. because I'm tired. ;)

**Comment by julienmalik** [comment]
Funny commit message apart, are you sure for the second part of your commit ?

If you shallow clone a branch, you can't afterwards git reset --hard to a specific revision, because in your local history you only have one commit.

**Comment by opi** [comment]
Sure, just thinking about that too

**Pull request merged**
